# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "alexsmobs:snow_leopard",
    "galosphere:berserker",
    "goety:quick_growing_vine",
    "ambientadditions:moustached_tamarin",
    "ambientadditions:yeti_crab",
    "savage_and_ravage:trickster",
    "illusion_onslaught:meteorite",
    "alexsmobs:endergrade",
    "minecraft:horse",
    "goety:reaper_servant",
    "ambientadditions:ring_tailed_lemur",
    "goated:geep",
    "goety:mini_ghast",
    "minecraft:llama",
    "alexsmobs:skreecher",
    "minecraft:tadpole",
    "kobolds:kobold_skeleton",
    "aquamirae:maw",
    "environmental:yak",
    "goety:frozen_zombie_servant",
    "alexsmobs:hammerhead_shark",
    "alexsmobs:grizzly_bear",
    "alexsmobs:murmur_head",
    "finsandtails:wherble",
    "environmental:duck",
    "iter_rpg:carcass",
    "goety:zombie_servant",
    "goblintraders:vein_goblin_trader",
    "iter_rpg:giant_spider",
    "galosphere:spectre",
    "minecraft:mooshroom",
    "illusion_onslaught:chaos_totem",
    "adventure_legacy:thunder_storm_skeleton",
    "goety:zpiglin_brute_servant",
    "minecraft:axolotl",
    "alexsmobs:gorilla",
    "goety:haunted_skull",
    "goety:icy_spider_servant",
    "goety:vizier",
    "quark:crab",
    "alexsmobs:cosmic_cod",
    "iter_rpg:marrow_mite",
    "sullysmod:lanternfish",
    "alexsmobs:kangaroo",
    "finsandtails:gopjet",
    "ecologics:coconut_crab",
    "illagerinvasion:inquisitor",
    "adventure_legacy:cartographer_illager",
    "alexsmobs:hummingbird",
    "collectorsreap:platinum_bass",
    "goety:leapleaf",
    "iter_rpg:chaos_apparition",
    "goety:trampler",
    "ambientadditions:longhorn_cowfish",
    "goety:sunken_skeleton_servant",
    "alexsmobs:crow",
    "goety:brood_mother_servant",
    "alexsmobs:guster",
    "goety:blackguard_servant",
    "goety:drowned_necromancer_servant",
    "goety:vanguard_servant",
    "iter_rpg:hydra_bubble",
    "iter_rpg:demonspine",
    "minecraft:chicken",
    "iter_rpg:void_portal",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "alexsmobs:emu",
    "tinyskeletons:baby_stray",
    "iter_rpg:pebblehead",
    "buzzier_bees:moobloom",
    "goety:wither_necromancer",
    "goety:brood_mother",
    "queen_bee:queen_bee",
    "alexsmobs:flutter",
    "minecraft:hoglin",
    "goety:totemic_bomb",
    "goety:hostile_black_wolf",
    "ambientadditions:nine_banded_armadillo",
    "goety:crusher_servant",
    "minecraft:zombified_piglin",
    "habitat:pooka",
    "iter_rpg:void_elemental",
    "minecraft:sheep",
    "goety:crypt_slime",
    "ambientadditions:marten",
    "ambientadditions:shame_faced_crab",
    "quark:foxhound",
    "goety:wartling",
    "goety:haunt",
    "alexsmobs:bone_serpent_part",
    "illagerinvasion:basher",
    "alexsmobs:raccoon",
    "minecraft:ravager",
    "alexsmobs:bone_serpent",
    "finsandtails:penglil",
    "goety:border_wraith_servant",
    "crabbersdelight:crab",
    "crittersandcompanions:dragonfly",
    "finsandtails:siderol_whiskered_snail",
    "alexsmobs:mudskipper",
    "finsandtails:banded_redback_shrimp",
    "goety:skeleton_wolf",
    "tinyskeletons:baby_skeleton",
    "alexsmobs:crimson_mosquito",
    "goety:black_wolf",
    "alexsmobs:jerboa",
    "crittersandcompanions:otter",
    "piglinproliferation:piglin_traveler",
    "goety:wildfire",
    "goety:witch_servant",
    "goety:grave_golem",
    "illusion_onslaught:havocist",
    "finsandtails:blu_wee",
    "ambientadditions:white_fruit_bat",
    "alexsmobs:comb_jelly",
    "illusion_onslaught:spirit",
    "brewery:beer_elemental",
    "goety:quick_growing_kelp",
    "alexsmobs:enderiophage",
    "alexsmobs:sunbird",
    "goety:iceologer_servant",
    "minecraft:cat",
    "minecraft:tropical_fish",
    "iter_rpg:insatiable",
    "iter_rpg:unbound_soul",
    "dungeonsdelight:monster_yam",
    "ambientadditions:siamang_gibbon",
    "minecraft:zombie_villager",
    "ambientadditions:aye_aye",
    "iter_rpg:mudkin",
    "environmental:zebra",
    "goety:sorcerer",
    "iter_rpg:aura_mobspawn",
    "alexsmobs:froststalker",
    "minecraft:giant",
    "alexsmobs:lobster",
    "alexsmobs:seagull",
    "iter_rpg:mournstone",
    "goety:bear_servant",
    "goety:wraith",
    "aquamirae:tortured_soul",
    "illagerinvasion:sorcerer",
    "iter_rpg:caltrop_thrown",
    "finsandtails:teal_arrowfish",
    "ambientadditions:mole",
    "iter_rpg:peeper",
    "minecraft:husk",
    "mca:female_zombie_villager",
    "adventure_legacy:ancient_enderman",
    "iter_rpg:aura_tearburst",
    "savage_and_ravage:skeleton_villager",
    "illusion_onslaught:undead_sorcer",
    "ambientadditions:leaf_frog_tadpole",
    "minecraft:donkey",
    "iter_rpg:prismauler",
    "finsandtails:river_pebble_snail",
    "goety:wither_skeleton_servant",
    "minecraft:piglin_brute",
    "aquamirae:golden_moth",
    "illusion_onslaught:havocexplosion",
    "goety:malghast",
    "iter_rpg:aura_soulfire",
    "galosphere:sparkle",
    "finsandtails:swamp_mucker",
    "goety:neollager",
    "iter_rpg:griever",
    "finsandtails:phantom_nudibranch",
    "collectorsreap:chieftain_crab",
    "goety:cairn_necromancer",
    "alexsmobs:frilled_shark",
    "sullysmod:tortoise",
    "goety:conquillager",
    "alexsmobs:bald_eagle",
    "alexsmobs:blobfish",
    "goety:wight",
    "ecologics:squirrel",
    "ambientadditions:cardigan_corgi",
    "environmental:slabfish",
    "alexsmobs:void_worm",
    "ambientadditions:pink_fairy_armadillo",
    "illusion_onslaught:spirit_support",
    "minecraft:parrot",
    "aquamirae:spinefish",
    "adventure_legacy:illager_mage",
    "alexsmobs:centipede_head",
    "goety:blaze_servant",
    "goety:polar_bear_servant",
    "goety:evoker_servant",
    "adventure_legacy:pirate",
    "alexsmobs:banana_slug",
    "savage_and_ravage:griefer",
    "savage_and_ravage:iceologer",
    "ambientadditions:sloth_bear",
    "illagerinvasion:surrendered",
    "goety:bone_spider_servant",
    "alexsmobs:bunfungus",
    "illusion_onslaught:chaos_explosion",
    "minecraft:mule",
    "ribbits:ribbit",
    "minecraft:vindicator",
    "goety:jungle_zombie_servant",
    "alexsmobs:flying_fish",
    "crittersandcompanions:leaf_insect",
    "quark:forgotten",
    "ambientadditions:harlequin_shrimp",
    "iter_rpg:sorrowsealed",
    "goety:cryologer",
    "pneumaticcraft:guard_drone",
    "iter_rpg:small_scallop",
    "iter_rpg:weeper",
    "iter_rpg:star_worm_segment",
    "aquamirae:luminous_jelly",
    "alexsmobs:terrapin",
    "illagerinvasion:firecaller",
    "goety:crusher",
    "finsandtails:golden_river_ray",
    "mca:grim_reaper",
    "piglinproliferation:piglin_alchemist",
    "atmospheric:cochineal",
    "goety:necromancer",
    "minecraft:pig",
    "alexsmobs:alligator_snapping_turtle",
    "goety:web_spider",
    "goety:glacial_wall",
    "atmospheric:tetra",
    "minecraft:cod",
    "alexsmobs:platypus",
    "minecraft:cow",
    "alexsmobs:rocky_roller",
    "goety:inferno",
    "alexsmobs:soul_vulture",
    "iter_rpg:windswirl",
    "goety:magma_cube_servant",
    "alexsmobs:blue_jay",
    "minecraft:salmon",
    "crittersandcompanions:dumbo_octopus",
    "ambientadditions:spider_tailed_adder",
    "alexsmobs:anteater",
    "alexsmobs:rain_frog",
    "minecraft:rabbit",
    "horse_colors:horse_felinoid",
    "minecraft:pillager",
    "minecraft:zoglin",
    "savage_and_ravage:creepie",
    "goety:crone",
    "iter_rpg:water_elemental",
    "ambientadditions:red_river_hog",
    "alexsmobs:leafcutter_ant",
    "goety:ice_golem",
    "thermal:basalz",
    "eidolon:wraith",
    "kobolds:kobold_zombie",
    "goety:storm_caster",
    "ambientadditions:veiled_chameleon",
    "horse_colors:mule",
    "eidolon:slimy_slug",
    "goety:haunted_armor",
    "illagerinvasion:archivist",
    "aquamirae:captain_cornelia",
    "illusion_onslaught:cultoliger",
    "goety:vindicator_servant",
    "finsandtails:wee_wee",
    "goety:hoglin_servant",
    "alexsmobs:gazelle",
    "minecraft:sniffer",
    "goety:damned",
    "collectorsreap:tiger_prawn",
    "goety:spider_egg",
    "goety:cave_spider_servant",
    "iter_rpg:fiend",
    "swampier_swamps:dragonfly",
    "goety:hellhound",
    "goety:spider_servant",
    "illusion_onslaught:flail",
    "illagerinvasion:necromancer",
    "ambientadditions:chocolate_chip_starfish",
    "alexsmobs:seal",
    "environmental:deer",
    "adventure_legacy:mountaineer_illager_2",
    "adventure_legacy:mountaineer_illager_1",
    "goety:cairn_necromancer_servant",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "minecraft:trader_llama",
    "iter_rpg:scab",
    "goety:ally_vex",
    "goety:ravager",
    "goblintraders:goblin_trader",
    "meadow:wooly_sheep",
    "iter_rpg:aura_boulder",
    "alexsmobs:maned_wolf",
    "goety:necromancer_servant",
    "minecraft:dolphin",
    "neapolitan:plantain_spider",
    "goety:bound_evoker",
    "alexsmobs:gelada_monkey",
    "goety:geomancer_servant",
    "finsandtails:flatback_sucker",
    "alexsmobs:dropbear",
    "goety:apostle",
    "alexsmobs:tiger",
    "goety:pillager_servant",
    "eidolon:raven",
    "crittersandcompanions:jumping_spider",
    "goety:crypt_slime_servant",
    "buzzier_bees:grizzly_bear",
    "goety:whisperer",
    "minecraft:bee",
    "alexsmobs:devils_hole_pupfish",
    "pneumaticcraft:harvesting_drone",
    "goety:ravaged",
    "minecraft:illusioner",
    "goety:border_wraith",
    "goety:maverick",
    "illusion_onslaught:shockwave",
    "takesapillage:skirmisher",
    "alexsmobs:bison",
    "pneumaticcraft:amadrone",
    "minecraft:drowned",
    "iter_rpg:dwarf",
    "ambientadditions:flying_fish",
    "goety:skeleton_villager_servant",
    "goety:bone_spider",
    "iter_rpg:magic_squid",
    "environmental:tapir",
    "iter_rpg:fleshmite",
    "alexsmobs:tusklin",
    "finsandtails:rubber_belly_glider",
    "alexsmobs:underminer",
    "goety:twilight_goat",
    "sullysmod:bouldering_zombie",
    "spelunkery:dust_bunny",
    "minecraft:wandering_trader",
    "goety:minister",
    "environmental:reindeer",
    "ambientadditions:naked_mole_rat",
    "finsandtails:papa_wee",
    "conjurer_illager:conjurer",
    "goety:vampire_bat",
    "goety:hostile_redstone_golem",
    "crittersandcompanions:sea_bunny",
    "finsandtails:pea_wee",
    "goety:carrion_maggot",
    "goety:carrion_fly",
    "goety:armored_ravager",
    "goety:poison_quill_vine",
    "ambientadditions:iiwi",
    "crittersandcompanions:red_panda",
    "goety:wither_necromancer_servant",
    "minecraft:pufferfish",
    "horse_colors:donkey",
    "minecraft:fox",
    "iter_rpg:harvest_spiral",
    "immersiveengineering:bulwark",
    "adventure_legacy:mountaineer_illager",
    "alexsmobs:warped_toad",
    "tinyskeletons:baby_wither_skeleton",
    "goety:warlock",
    "goety:drowned_servant",
    "iter_rpg:bloated",
    "immersiveengineering:fusilier",
    "goety:muck_wraith",
    "goety:vindicator_chef_servant",
    "alexsmobs:cockroach",
    "goety:storm_caster_servant",
    "finsandtails:spindly_gem_crab",
    "neapolitan:chimpanzee",
    "finsandtails:white_bull_crab",
    "goety:poison_anemone",
    "ambientadditions:pancake_slug",
    "alexsmobs:capuchin_monkey",
    "goety:insect_swarm",
    "goety:irk",
    "minecraft:polar_bear",
    "goety:guardian_servant",
    "sullysmod:piranha",
    "goety:wraith_servant",
    "goety:ghast_servant",
    "minecraft:turtle",
    "goety:haunted_armor_servant",
    "quark:wraith",
    "finsandtails:crowned_horatee",
    "goety:redstone_monstrosity",
    "alexsmobs:rattlesnake",
    "ambientadditions:pinocchio_anole",
    "adventure_legacy:archer_illager",
    "eidolon:giant_skeleton",
    "iter_rpg:grimhook",
    "alexsmobs:potoo",
    "alexsmobs:fly",
    "illusion_onslaught:illusioner",
    "quark:shiba",
    "alexsmobs:straddler",
    "iter_rpg:blob",
    "alexsmobs:sea_bear",
    "goety:web_spider_servant",
    "ambientadditions:blue_spotted_stingray",
    "goety:wind_caller_servant",
    "alexsmobs:sugar_glider",
    "supplementaries:red_merchant",
    "sullysmod:jungle_spider",
    "pneumaticcraft:programmable_controller",
    "aquamirae:eel",
    "savage_and_ravage:executioner",
    "goety:redstone_cube",
    "alexsmobs:orca",
    "goety:skull_lord",
    "finsandtails:ornate_bugfish",
    "illagerinvasion:alchemist",
    "minecraft:bat",
    "alexsmobs:cosmaw",
    "goety:ripper",
    "goety:hostile_redstone_monstrosity",
    "goety:skeleton_servant",
    "eidolon:zombie_brute",
    "iter_rpg:scallop",
    "alexsmobs:skunk",
    "aquamirae:anglerfish",
    "environmental:koi",
    "goety:ally_trampler",
    "alexsmobs:tasmanian_devil",
    "goety:ally_irk",
    "goety:zombie_ravager",
    "alexsmobs:stradpole",
    "ecologics:penguin",
    "illusion_onslaught:chaosbringer",
    "embers:ancient_golem",
    "goety:mossy_skeleton_servant",
    "minecraft:panda",
    "goety:reaper",
    "alexsmobs:moose",
    "illusion_onslaught:ice_crystal",
    "alexsmobs:shoebill",
    "alexsmobs:farseer",
    "iter_rpg:solsphere",
    "goety:bound_iceologer",
    "iter_rpg:fire_elemental",
    "alexsmobs:warped_mosco",
    "immersiveengineering:commando",
    "meadow:wooly_cow",
    "finsandtails:high_finned_blue",
    "goety:black_beast",
    "iter_rpg:grimace",
    "ambientadditions:mata_mata",
    "ambientadditions:leaf_frog",
    "adventure_legacy:bandit",
    "iter_rpg:prismaw",
    "galosphere:preserved",
    "alexsmobs:komodo_dragon",
    "iter_rpg:grim_boulder",
    "aquamirae:maze_mother",
    "goety:zpiglin_servant",
    "quark:stoneling",
    "illusion_onslaught:havocist_clone",
    "goety:husk_servant",
    "iter_rpg:spiderling",
    "alexsmobs:crocodile",
    "quark:toretoise",
    "illusion_onslaught:blackhole",
    "alexsmobs:triops",
    "iter_rpg:earth_boulder",
    "alexsmobs:rhinoceros",
    "goety:slime_servant",
    "galosphere:specterpillar",
    "alexsmobs:mimicube",
    "collectorsreap:urchin",
    "ambientadditions:stag_beetle",
    "thermal:blizz",
    "iter_rpg:debug_mobmorph",
    "finsandtails:mudhorse",
    "finsandtails:red_bull_crab",
    "finsandtails:wandering_sailor",
    "vinery:mule",
    "ambientadditions:pembroke_corgi",
    "minecraft:frog",
    "crittersandcompanions:shima_enaga",
    "iter_rpg:star_worm",
    "illagerinvasion:marauder",
    "alexsmobs:mimic_octopus",
    "goety:phantom_servant",
    "alexsmobs:void_worm_part",
    "pneumaticcraft:collector_drone",
    "iter_rpg:axebeak",
    "finsandtails:night_light_squid",
    "vinery:wandering_winemaker",
    "goety:totemic_wall",
    "goety:tropical_slime_servant",
    "aquamirae:pillagers_patrol",
    "illusion_onslaught:chaos_slash",
    "minecraft:evoker",
    "alexsmobs:tarantula_hawk",
    "crittersandcompanions:ferret",
    "adventure_legacy:cartographer_illager_clone",
    "alexsmobs:cachalot_whale",
    "ambientadditions:opah",
    "takesapillage:legioner",
    "goety:piker",
    "adventure_legacy:captain_pirate",
    "iter_rpg:air_elemental",
    "goety:redstone_golem",
    "goety:heretic",
    "goety:snapper",
    "finsandtails:flatback_leaf_snail",
    "goety:zombie_villager_servant",
    "alexsmobs:anaconda",
    "thermal:blitz",
    "illusion_onslaught:cultoliger_shadows",
    "goety:bone_lord",
    "iter_rpg:event_spawn",
    "minecraft:goat",
    "mca:male_zombie_villager",
    "iter_rpg:revenant",
    "iter_rpg:chain_handle",
    "goety:skeleton_pillager",
    "alexsmobs:mantis_shrimp",
    "meadow:water_buffalo",
    "eidolon:necromancer",
    "goety:envioker",
    "goety:preacher",
    "illagerinvasion:invoker",
    "ambientadditions:napoleon_wrasse",
    "goety:stray_servant",
    "goety:obsidian_monolith",
    "ambientadditions:blunthead_tree_snake",
    "finsandtails:vibra_wee",
    "alexsmobs:toucan",
    "habitat:passerine",
    "goety:tormentor",
    "iter_rpg:earth_elemental",
    "alexsmobs:murmur",
    "iter_rpg:damage_test",
    "pneumaticcraft:drone",
    "illusion_onslaught:chaos_shockwave",
    "iter_rpg:forest_vines",
    "goety:zombie_vindicator",
    "adventure_legacy:bandit_swordsman",
    "goety:vizier_clone",
    "collectorsreap:clam",
    "alexsmobs:mungus",
    "crittersandcompanions:koi_fish",
    "illusion_onslaught:earth",
    "alexsmobs:caiman",
    "pneumaticcraft:logistics_drone",
    "alexsmobs:spectre",
    "alexsmobs:catfish",
    "goety:inquillager",
    "minecraft:piglin",
    "alexsmobs:skelewag",
    "goety:icy_spider",
    "takesapillage:archer",
    "alexsmobs:elephant",
    "illagerinvasion:provoker",
    "minecraft:zombie_horse",
    "goety:wavewhisperer",
    "ambientadditions:rubber_ducky_isopod",
    "minecraft:camel",
    "adventure_legacy:ancient_golem",
    "goety:muck_wraith_servant",
    "ambientadditions:rabbit_snail",
    "minecraft:ocelot",
    "minecraft:wolf",
    "ambientadditions:giant_land_snail",
    "goety:squall_golem"
]
