"Toggle whether or not iron golems are impervious to arrows" = true
"Toggle whether or not iron golems have increased attack range" = true
#Define whether or not the text the player receives when attempting to spawn the wither will show what dimensions the wither is spawnable in.
"Show valid dimensions:" = true

