
[Text]

	[Text.Pause]
		pause_enabled = true
		pause_centered = false
		#Range: -16777216 ~ -1
		pause_now_color = -16711681
		#Range: 0.0 ~ 1.0
		pause_height_coefficient_screen_height = 1.0
		#Range: -32768 ~ 32767
		pause_height_constant = -15
		#Range: 0.0 ~ 1.0
		pause_width_coefficient_screen_width = 0.0
		#Range: -32768 ~ 32767
		pause_width_constant = 2

	[Text.Title]
		title_enabled = true
		title_centered = false
		#Range: -16777216 ~ -1
		title_now_color = -16711681
		#Range: 0.0 ~ 1.0
		title_height_coefficient_screen_height = 0.0
		#Range: -32768 ~ 32767
		title_height_constant = 5
		#Range: 0.0 ~ 1.0
		title_width_coefficient_screen_width = 0.0
		#Range: -32768 ~ 32767
		title_width_constant = 2

[Popup]
	#Allowed Values: TOAST, OVERLAY, DISABLED
	musicPopupStyle = "DISABLED"
	#Allowed Values: TOAST, OVERLAY, DISABLED
	recordPopupStyle = "DISABLED"

	[Popup.Toast]
		#Range: 500 ~ 20000
		toastExpiration = 5000
		defaultToastIcon = "minecraft:music_disc_far"
		silentToast = true

