#A list of features to ways connect.
#路可以连接特征的名单。
#example: "minecraft:village"
features = ["minecraft:village", "towns_and_towers:town", "tesit:tavern"]
#Way always connect village?
#路是否总是连接村庄？
connectVillage = true
#A maximum number of features to connect in a region.
#一个区域内连接特征的最大数量
#Range: 0 ~ 10
connectFeaturesNum = 3
#Other information on the way sign.
#路牌上的其他信息。
#example: "[HELLO]Welcome to Minecraft World!"
notes = ["[HELLO]Welcome to Minecraft World!"]

